DROP TABLE preliminary;

-- https://www.w3schools.com/sql/sql_create_table.asp
CREATE TABLE preliminary (
	as_of_year text,
	respondent_id text,
	agency_name text,
	agency_abbr text,
	agency_code text,
	loan_type_name text,
	loan_type text,
	property_type_name text,
	property_type text,
	loan_purpose_name text,
	loan_purpose text,
	owner_occupancy_name text,
	owner_occupancy text,
	loan_amount_000s text,
	preapproval_name text,
	preapproval text,
	action_taken_name text,
	action_taken text,
	msamd_name text,
	msamd text,
	state_name text,
	state_abbr text,
	state_code text,
	county_name text,
	county_code text,
	census_tract_number text,
	applicant_ethnicity_name text,
	applicant_ethnicity text,
	co_applicant_ethnicity_name text,
	co_applicant_ethnicity text,
	applicant_race_name_1 text,
	applicant_race_1 text,
	applicant_race_name_2 text,
	applicant_race_2 text,
	applicant_race_name_3 text,
	applicant_race_3 text,
	applicant_race_name_4 text,
	applicant_race_4 text,
	applicant_race_name_5 text,
	applicant_race_5 text,
	co_applicant_race_name_1 text,
	co_applicant_race_1 text,
	co_applicant_race_name_2 text,
	co_applicant_race_2 text,
	co_applicant_race_name_3 text,
	co_applicant_race_3 text,
	co_applicant_race_name_4 text,
	co_applicant_race_4 text,
	co_applicant_race_name_5 text,
	co_applicant_race_5 text,
	applicant_sex_name text,
	applicant_sex text,
	co_applicant_sex_name text,
	co_applicant_sex text,
	applicant_income_000s text,
	purchaser_type_name text,
	purchaser_type text,
	denial_reason_name_1 text,
	denial_reason_1 text,
	denial_reason_name_2 text,
	denial_reason_2 text,
	denial_reason_name_3 text,
	denial_reason_3 text,
	rate_spread text,
	hoepa_status_name text,
	hoepa_status text,
	lien_status_name text,
	lien_status text,
	edit_status_name text,
	edit_status text,
	sequence_number text,
	population text,
	minority_population text,
	hud_median_family_income text,
	tract_to_msamd_income text,
	number_of_owner_occupied_units text,
	number_of_1_to_4_family_units text,
	application_date_indicator text
);

-- https://neon.tech/postgresql/postgresql-tutorial/import-csv-file-into-posgresql-table
\COPY preliminary FROM 'hmda_2017_nj_all-records_labels.csv' DELIMITER ',' CSV HEADER

ALTER TABLE preliminary
ADD COLUMN id SERIAL PRIMARY KEY;
